//! 嵌入 Windows 图标；扫描根目录 `fonts` 生成内置字体字节表。

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=assets/icon.ico");
    println!("cargo:rerun-if-changed=assets/icon.png");
    println!("cargo:rerun-if-changed=assets/app.manifest");
    println!("cargo:rerun-if-changed=../../fonts");

    generate_builtin_fonts();

    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        let mut res = winresource::WindowsResource::new();
        res.set_icon("assets/icon.ico");
        res.set_manifest_file("assets/app.manifest");
        // Windows Explorer reads these fields from the PE version resource.
        // Keep the technical Cargo crate name separate from the product name.
        res.set("FileDescription", "DeskHud");
        res.set("ProductName", "DeskHud");
        res.set("InternalName", "DeskHud");
        res.set("OriginalFilename", "deskhud.exe");
        res.set("CompanyName", "KO.EIKA");
        if let Err(e) = res.compile() {
            println!("cargo:warning=embed icon.ico failed: {e}");
        }
    }
}

fn generate_builtin_fonts() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let fonts_dir = manifest.join("../../fonts");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("builtin_fonts_gen.rs");

    let mut files: Vec<PathBuf> = Vec::new();
    if fonts_dir.is_dir() {
        collect_font_files(&fonts_dir, &mut files);
    }
    files.sort();

    for f in &files {
        println!("cargo:rerun-if-changed={}", f.display());
    }

    let mut src = String::from(
        "// @generated by build.rs — do not edit\n\
         pub static BUILTIN_FONT_FILES: &[(&str, &[u8])] = &[\n",
    );
    for path in &files {
        let name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("font.bin");
        // 相对 manifest，供 include_bytes 使用正斜杠
        let rel = path
            .strip_prefix(&manifest)
            .unwrap_or(path)
            .to_string_lossy()
            .replace('\\', "/");
        src.push_str(&format!(
            "    (\"{name}\", include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{rel}\"))),\n"
        ));
    }
    src.push_str("];\n");

    fs::write(&out_file, src).expect("write builtin_fonts_gen.rs");
}

fn collect_font_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = fs::read_dir(dir) else {
        return;
    };
    for entry in rd.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_font_files(&path, out);
            continue;
        }
        let Some(ext) = path.extension().and_then(|e| e.to_str()) else {
            continue;
        };
        let ext = ext.to_ascii_lowercase();
        if matches!(ext.as_str(), "ttf" | "otf" | "ttc") {
            out.push(path);
        }
    }
}
