//! 嵌入 Windows 图标与仓库内唯一的 Inter 字体资源。

use std::env;
use std::fs;
use std::path::PathBuf;

const INTER_FONT: &str = "../../assets/fonts/Inter.ttc";

fn main() {
    println!("cargo:rerun-if-changed=../../assets/icon.ico");
    println!("cargo:rerun-if-changed=../../assets/icon.png");
    println!("cargo:rerun-if-changed=../../assets/app.manifest");
    println!("cargo:rerun-if-changed={INTER_FONT}");

    generate_builtin_fonts();

    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        let mut res = winresource::WindowsResource::new();
        res.set_icon("../../assets/icon.ico");
        res.set_manifest_file("../../assets/app.manifest");
        // Windows Explorer reads these fields from the PE version resource.
        // Keep the technical Cargo crate name separate from the product name.
        res.set("FileDescription", "DeskHud");
        res.set("ProductName", "DeskHud");
        res.set("InternalName", "DeskHud");
        res.set("OriginalFilename", "deskhud.exe");
        res.set("CompanyName", "KO.EIKA");
        if let Err(e) = res.compile() {
            println!("cargo:warning=embed icon.ico failed: {e}");
        }
    }
}

fn generate_builtin_fonts() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("builtin_fonts_gen.rs");

    let mut src = String::from(
        "// @generated by build.rs — do not edit\n\
         pub static BUILTIN_FONT_FILES: &[(&str, &[u8])] = &[\n",
    );
    src.push_str(
        "    (\"Inter.ttc\", include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../assets/fonts/Inter.ttc\"))),\n",
    );
    src.push_str("];\n");

    fs::write(&out_file, src).expect("write builtin_fonts_gen.rs");
}
