//! 多源文案合并：外壳 PO/MO 目录 + 已加载包 gettext 目录。

use std::collections::BTreeMap;

use super::{Locale, MessageKey, catalogs, normalize_locale_tag};

/// 动态键值表（按 locale 分桶）；缺键回退到 `en-US`/`en`。
#[derive(Debug, Clone, Default)]
pub struct CatalogStore {
    /// locale 标签（如 `zh-CN` / `en`）→ 键 → 文案。
    layers: BTreeMap<String, BTreeMap<String, String>>,
}

impl CatalogStore {
    /// 空目录。
    pub fn new() -> Self {
        Self::default()
    }

    /// Returns all valid language tags currently present in the store.
    pub fn locales(&self) -> Vec<String> {
        self.layers.keys().cloned().collect()
    }

    /// 合并一层键值（后者覆盖同键）。
    pub fn merge_layer(&mut self, locale: &str, messages: &BTreeMap<String, String>) {
        let tag = normalize_locale_tag(locale);
        if tag.is_empty() {
            return;
        }
        let bucket = self.layers.entry(tag).or_default();
        for (k, v) in messages {
            bucket.insert(k.clone(), v.clone());
        }
    }

    /// 合并包目录；`prefix` 形如 `pet.org.id.` / `hud.org.id.`。
    pub fn merge_prefixed(
        &mut self,
        locale: &str,
        prefix: &str,
        messages: &BTreeMap<String, String>,
    ) {
        let mut prefixed = BTreeMap::new();
        for (k, v) in messages {
            prefixed.insert(format!("{prefix}{k}"), v.clone());
        }
        self.merge_layer(locale, &prefixed);
    }

    /// 查动态键；顺序：当前 locale → 语言族 → `en-US`/`en` → `None`。
    pub fn get(&self, locale: Locale, key: &str) -> Option<&str> {
        for tag in locale.fallback_tags() {
            if let Some(v) = self.layers.get(&tag).and_then(|m| m.get(key)) {
                return Some(v.as_str());
            }
        }
        for tag in ["en-US", "en"] {
            if !locale.fallback_tags().iter().any(|t| t == tag)
                && let Some(v) = self.layers.get(tag).and_then(|m| m.get(key))
            {
                return Some(v.as_str());
            }
        }
        None
    }

    /// 外壳固定键（静态目录）。
    pub fn t_shell(locale: Locale, key: MessageKey) -> &'static str {
        catalogs::lookup(locale, key)
    }

    /// 动态键；缺失时返回 `fallback`。
    pub fn t<'a>(&'a self, locale: Locale, key: &str, fallback: &'a str) -> &'a str {
        if let Some(value) = self.get(locale, key) {
            return value;
        }
        if fallback != key || (!key.starts_with("InputKey") && !key.contains('.')) {
            return fallback;
        }
        default_dynamic_message(key)
    }
}

/// Returns a safe Chinese fallback for common runtime-only keys.
///
/// Runtime event labels are generated by pets and may be displayed even when
/// an optional catalog is missing. Never expose the internal key to users.
fn default_dynamic_message(key: &str) -> &'static str {
    if let Some(number) = key.strip_prefix("InputKey.NumpadDigit.") {
        return Box::leak(format!("小键盘 {number}").into_boxed_str());
    }
    if let Some(number) = key.strip_prefix("InputKey.F")
        && number.parse::<u8>().is_ok()
    {
        return Box::leak(format!("F{number}").into_boxed_str());
    }
    match key {
        "InputKey.Escape" => "退出",
        "InputKey.Tab" => "制表",
        "InputKey.Enter" => "回车",
        "InputKey.Space" => "空格",
        "InputKey.Backspace" => "退格",
        "InputKey.Delete" => "删除",
        "InputKey.Insert" => "插入",
        "InputKey.Clear" => "清除",
        "InputKey.ArrowUp" => "上",
        "InputKey.ArrowDown" => "下",
        "InputKey.ArrowLeft" => "左",
        "InputKey.ArrowRight" => "右",
        "InputKey.Home" => "首页",
        "InputKey.End" => "末页",
        "InputKey.PageUp" => "上页",
        "InputKey.PageDown" => "下页",
        "InputKey.Shift" => "Shift",
        "InputKey.Ctrl" => "Ctrl",
        "InputKey.Alt" => "Alt",
        "InputKey.Super" => "Win",
        "InputKey.CapsLock" => "大写锁定",
        "InputKey.NumLock" => "数字锁定",
        "InputKey.NumpadEnter" => "数字回车",
        "InputKey.PrintScreen" => "截屏",
        "InputKey.ScrollLock" => "滚动锁定",
        "InputKey.Pause" => "暂停",
        "InputKey.ContextMenu" => "菜单",
        "InputKeyPrimary" => "左键",
        "InputKeySecondary" => "右键",
        "InputKeyMiddle" => "中键",
        "InputKeyWheelUp" => "滚轮上",
        "InputKeyWheelDown" => "滚轮下",
        "InputKey.Command" => "Command",
        "InputKey.Option" => "Option",
        "InputKey.Primary" => "左键",
        "InputKey.Secondary" => "右键",
        "InputKey.Middle" => "中键",
        "InputKey.WheelUp" => "滚轮上",
        "InputKey.WheelDown" => "滚轮下",
        "InputKeyPress" => "按键",
        _ => "未翻译",
    }
}

/// UI / 文件用的 locale 标签。
pub fn locale_tag(locale: Locale) -> String {
    locale.tag()
}

/// 尝试的 locale 文件名（含别名）。
pub fn locale_file_candidates(locale: Locale) -> Vec<String> {
    locale.fallback_tags()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn merge_prefix_and_fallback() {
        let mut store = CatalogStore::new();
        let mut zh = BTreeMap::new();
        zh.insert("display_name".into(), "酷猫".into());
        store.merge_prefixed("zh-CN", "pet.example.cat.", &zh);

        assert_eq!(
            store.get(Locale::ZhCn, "pet.example.cat.display_name"),
            Some("酷猫")
        );
        assert_eq!(store.get(Locale::En, "pet.example.cat.display_name"), None);
        assert_eq!(
            store.t(Locale::En, "pet.example.cat.display_name", "Cat"),
            "Cat"
        );
        assert_eq!(
            CatalogStore::t_shell(Locale::ZhCn, MessageKey::AppName),
            catalogs::lookup(Locale::ZhCn, MessageKey::AppName)
        );
    }

    #[test]
    fn all_shell_keys_have_locale_entries_or_english_fallback() {
        for key in MessageKey::ALL {
            let debug_key = format!("{key:?}");
            assert_ne!(catalogs::lookup(Locale::En, *key), debug_key);
            assert_ne!(catalogs::lookup(Locale::ZhCn, *key), debug_key);
        }
    }

    #[test]
    fn dynamic_variant_falls_back_to_language_then_english() {
        let mut store = CatalogStore::new();
        let mut ja = BTreeMap::new();
        ja.insert("only.ja".into(), "日本語".into());
        store.merge_layer("ja", &ja);
        let mut en = BTreeMap::new();
        en.insert("only.en".into(), "English".into());
        store.merge_layer("en", &en);
        assert_eq!(
            store.get(Locale::from_tag("ja-JP").unwrap(), "only.ja"),
            Some("日本語")
        );
        assert_eq!(
            store.get(Locale::from_tag("ja-JP").unwrap(), "only.en"),
            Some("English")
        );
        assert_eq!(Locale::from_tag("zh_CN").unwrap(), Locale::ZhCn);
    }

    #[test]
    fn english_uses_en_us_as_the_canonical_directory() {
        assert_eq!(Locale::En.tag(), "en-US");
        assert_eq!(locale_file_candidates(Locale::En), ["en-US", "en"]);
        assert_eq!(Locale::from_tag("en").unwrap(), Locale::En);
        assert_eq!(Locale::from_tag("en_US").unwrap(), Locale::En);
    }

    #[test]
    fn missing_runtime_key_never_leaks_the_internal_key() {
        let store = CatalogStore::new();
        assert_eq!(
            store.t(Locale::ZhCn, "InputKey.Escape", "InputKey.Escape"),
            "退出"
        );
        assert_eq!(
            store.t(Locale::ZhCn, "pet.example.unknown", "pet.example.unknown"),
            "未翻译"
        );
        assert_eq!(
            store.t(Locale::ZhCn, "pet.example.unknown", "默认中文"),
            "默认中文"
        );
    }
}
