[package]
name = "deskhud-native"
description = "DeskHud native application entry point."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "deskhud"
path = "src/main.rs"

[target.'cfg(windows)'.dependencies]
deskhud-platform-windows = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
deskhud-platform-macos = { workspace = true }

[target.'cfg(all(not(windows), not(target_os = "macos")))'.dependencies]
deskhud-platform-linux-gtk = { workspace = true }
